### ISSUE TITLE
HTTP Status 405 - HTTP method GET is not supported by this URL

### ISSUE THREAD

**Issue by khansquare** [smsgh/ussd-java-sample#1]
Hello @Tochemey 
I was looking a sample application to understand USSD concepts and I found this project. I think your project will be helpful for me. I configured it as you described. But I'm getting "HTTP Status 405 - HTTP method GET is not supported by this URL" error on browser when I'm trying to access this url "http://localhost:8080/UssdSample/UssdHandler"
On the other hand, if I just opening "http://localhost:8080/UssdSample/", It is running.
I'm a beginner so can you please specify what's wrong with my configuration?

Regards

**Comment by mahendrakumarg** [comment]
Same Error I got!Please help me!

**Comment by Tochemey** [comment]
Hello,
This sample is to help Ghana developers to implement Ussd based application on our USSD Platform in Ghana. For that purpose you will need to have a USSD code on our platform from one of our local network. After that you will need to host this sample example on a Java Servlet container accessible via the internet so that the USSD Platform can connect and push the various USSD requests to your application.

**Comment by mahendrakumarg** [comment]
Hi sir i tried it.but same error!

**Comment by Tochemey** [comment]
@mahendrakumarg  It is obvious that there is no get method handler in the code. Please refer to the code: https://github.com/smsgh/ussd-java-sample/blob/master/src/ussd/sample/UssdHandler.java. It only handle post requests. Thanks

**Comment by mahendrakumarg** [comment]
@Tochemey  Please make it clear sir.Thanks
